### ISSUE TITLE
Added contact form

### ISSUE THREAD

**Issue by MustakimMasum** [firepicaso/RWD_Portfolio#4]
activities-

- added an html form
- added class for the form section

currently working on the styling of this section

**Comment by wacoo** [comment]
It is more of a suggestion, you didn't use ul for the form. Using ul for the form and li to separate the input fields makes it easier to fix the layout.

**Comment by samuelkinyanjui** [comment]
Please use new buttons with different formatting for the contact button

**Comment by Frelly0** [comment]
i would suggest these following:

- please provide required option on input and method, action

**Comment by MustakimMasum** [comment]
Thank you, guys. Really appreciate your input.
@wacoo @samuelkinyanjui @Frelly0
